#!/bin/sh -eu
set -eu

# We have multiple versions of Python in different testing environments.
#
# Netlify: has 3.5 and 3.7 with 3 being a symlink to 3.5
#  - problem: 3.5 has limited/broken pathlib support, our script fails
#
# Travis: the bionic runtime has no Python 3.7, no matter what their docs say,
# at least when invoked with "language: node_js".
# No `python` controllers affect that.
# But a bare `python3` works.
#
# Rather than play self-re-exec games with the Python script, we wrap it with
# this portability shim.

PyCommandName='standalone-update-website'
PyCommand="$(dirname "$0")/$PyCommandName"
PyMinimum='(3, 6)'

progname="$(basename "$0" .sh)"
note() { printf >&2 '%s: %s\n' "$progname" "$*"; }

okay=false
for py_interp in python3 python3.8 python3.7 python3.6
do
  if $py_interp 2>/dev/null <<EOTEST
import sys
MIN_PY = $PyMinimum
if sys.version_info < MIN_PY:
  sys.exit(1)
EOTEST
  then
    okay=true
    break
  fi
done

if ! $okay; then
  note "unable to find an acceptable [>= $PyMinimum] Python interpreter"
  exit 1
fi

note "Using Python interpreter $py_interp to run $PyCommand"
exec "$py_interp" "$PyCommand" "$@"
