import { MarkerType } from '@xyflow/react';
import type { NatsFlowScenario } from '../types';

export const requestReplyQueueGroupScenario: NatsFlowScenario = {
  description: 'Request with queue group - only one service responds (load balancing)',
  nodes: [
    {
      id: 'client',
      type: 'publisher',
      position: { x: 0, y: 120 },
      data: { label: 'Client' },
    },
    {
      id: 'server',
      type: 'server',
      position: { x: 180, y: 120 },
      data: { label: 'NATS' },
    },
    {
      id: 'service-1',
      type: 'service',
      position: { x: 360, y: 30 },
      data: { label: 'Service A' },
    },
    {
      id: 'service-2',
      type: 'service',
      position: { x: 360, y: 120 },
      data: { label: 'Service B' },
    },
    {
      id: 'service-3',
      type: 'service',
      position: { x: 360, y: 210 },
      data: { label: 'Service C' },
    },
  ],
  edges: [
    // Request cycles repeating every 18 seconds (3 requests × 6 seconds each)

    // CYCLE 1: Request goes to Service A
    {
      id: 'request-client-server-1',
      source: 'client',
      target: 'server',
      sourceHandle: 'request',
      targetHandle: 'request-in',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#f97316',
        animated: true,
        label: 'work.process',
        labelOffset: -20,
        labelColor: '#f97316',
        delay: 0,
        interval: 18000,
      },
    },
    {
      id: 'request-server-service-1-cycle1',
      source: 'server',
      target: 'service-1',
      sourceHandle: 'request-out',
      targetHandle: 'request',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#f97316',
        animated: true,
        delay: 1500,
        interval: 18000,
      },
    },
    {
      id: 'reply-service-1-server-cycle1',
      source: 'service-1',
      target: 'server',
      sourceHandle: 'reply',
      targetHandle: 'reply-in',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#10b981',
        animated: true,
        delay: 3000,
        interval: 18000,
      },
      style: { strokeDasharray: '5,5' },
    },
    {
      id: 'reply-server-client-1',
      source: 'server',
      target: 'client',
      sourceHandle: 'reply-out',
      targetHandle: 'reply',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#10b981',
        animated: true,
        label: '1 reply',
        labelOffset: 20,
        labelColor: '#10b981',
        delay: 4500,
        interval: 18000,
      },
      style: { strokeDasharray: '5,5' },
    },

    // CYCLE 2: Request goes to Service B
    {
      id: 'request-client-server-2',
      source: 'client',
      target: 'server',
      sourceHandle: 'request',
      targetHandle: 'request-in',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#f97316',
        animated: true,
        label: 'work.process',
        labelOffset: -20,
        labelColor: '#f97316',
        delay: 6000,
        interval: 18000,
      },
    },
    {
      id: 'request-server-service-2-cycle2',
      source: 'server',
      target: 'service-2',
      sourceHandle: 'request-out',
      targetHandle: 'request',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#f97316',
        animated: true,
        delay: 7500,
        interval: 18000,
      },
    },
    {
      id: 'reply-service-2-server-cycle2',
      source: 'service-2',
      target: 'server',
      sourceHandle: 'reply',
      targetHandle: 'reply-in',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#10b981',
        animated: true,
        delay: 9000,
        interval: 18000,
      },
      style: { strokeDasharray: '5,5' },
    },
    {
      id: 'reply-server-client-2',
      source: 'server',
      target: 'client',
      sourceHandle: 'reply-out',
      targetHandle: 'reply',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#10b981',
        animated: true,
        label: '1 reply',
        labelOffset: 20,
        labelColor: '#10b981',
        delay: 10500,
        interval: 18000,
      },
      style: { strokeDasharray: '5,5' },
    },

    // CYCLE 3: Request goes to Service C
    {
      id: 'request-client-server-3',
      source: 'client',
      target: 'server',
      sourceHandle: 'request',
      targetHandle: 'request-in',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#f97316',
        animated: true,
        label: 'work.process',
        labelOffset: -20,
        labelColor: '#f97316',
        delay: 12000,
        interval: 18000,
      },
    },
    {
      id: 'request-server-service-3-cycle3',
      source: 'server',
      target: 'service-3',
      sourceHandle: 'request-out',
      targetHandle: 'request',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#f97316',
        animated: true,
        delay: 13500,
        interval: 18000,
      },
    },
    {
      id: 'reply-service-3-server-cycle3',
      source: 'service-3',
      target: 'server',
      sourceHandle: 'reply',
      targetHandle: 'reply-in',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#10b981',
        animated: true,
        delay: 15000,
        interval: 18000,
      },
      style: { strokeDasharray: '5,5' },
    },
    {
      id: 'reply-server-client-3',
      source: 'server',
      target: 'client',
      sourceHandle: 'reply-out',
      targetHandle: 'reply',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#10b981',
        animated: true,
        label: '1 reply',
        labelOffset: 20,
        labelColor: '#10b981',
        delay: 16500,
        interval: 18000,
      },
      style: { strokeDasharray: '5,5' },
    },

    // Static edges showing all services are available
    {
      id: 'available-service-1',
      source: 'server',
      target: 'service-1',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#9ca3af',
        animated: false,
      },
      style: { strokeDasharray: '3,3', opacity: 0.3 },
    },
    {
      id: 'available-service-2',
      source: 'server',
      target: 'service-2',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#9ca3af',
        animated: false,
      },
      style: { strokeDasharray: '3,3', opacity: 0.3 },
    },
    {
      id: 'available-service-3',
      source: 'server',
      target: 'service-3',
      type: 'animated',
      markerEnd: { type: MarkerType.ArrowClosed },
      data: {
        color: '#9ca3af',
        animated: false,
      },
      style: { strokeDasharray: '3,3', opacity: 0.3 },
    },
  ],
};
